### ISSUE TITLE
Sock Error due to website update.

### ISSUE THREAD

**Issue by jwolfff** [Th3GrimRipp3r/ReaperCon#1]
## 
## \* /sockclose: insufficient parameters (line 206, bitcoin.mrc)
- /sockwrite: 'Kin.BitCoin.TickerData' not connected (line 222, bitcoin.mrc)

**Comment by Th3GrimRipp3r** [comment]
Will get Kin to look at it as soon as we can. An update will be uploaded as soon as possible.

**Comment by Zetacon** [comment]
Issue is nearly five years old. If still experiencing, please open new issue.
